name: Deliver main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Hub authentication
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_HUB_USERNAME }}/stargazer-plot:latest"
          build-args: |
            GIT_REVISION=${{ github.sha }}
